### ISSUE TITLE
Deploying Kcrow container using Helm is error

### ISSUE THREAD

**Issue by Frank-svg-dev** [kcrow-io/kcrow#21]
使用helm部署kcrow过程中发现日志内部报错，以及describe pod 报错， 如下：
describe pod
![image](https://github.com/user-attachments/assets/c81b3a33-ac0f-46e5-b390-736cac023667)

pod logs
`I1231 02:00:33.157585       1 daemon.go:30] CommitVersion: 8cf2aadaf6a69b4fb1bcc1e5b783b44ab315d98c
I1231 02:00:33.157739       1 daemon.go:33] CommitTime: 2024-12-30T20:30:22+08:00
I1231 02:00:33.157746       1 daemon.go:36] AppVersion: 8cf2aadaf6a69b4fb1bcc1e5b783b44ab315d98c
I1231 02:00:33.157753       1 daemon.go:41] Default max golang procs: 16
I1231 02:00:33.157817       1 daemon.go:44] Change max golang procs to 16
I1231 02:00:33.157836       1 daemon.go:86] Begin to initialize controller manager
I1231 02:00:33.183661       1 node.go:79] regist node callback cgroup
I1231 02:00:33.183700       1 namespace.go:69] regist namespace callback cgroup
I1231 02:00:33.183716       1 node.go:79] regist node callback ulimit
I1231 02:00:33.183723       1 namespace.go:69] regist namespace callback ulimit
I1231 02:00:33.183743       1 hub.go:36] registe controller 'cgroup'
I1231 02:00:33.183751       1 hub.go:36] registe controller 'ulimit'
I1231 02:00:33.183757       1 hub.go:36] registe controller 'vm-volume'
I1231 02:00:33.184432       1 daemon.go:97] Starting controller runtime manager
time="2024-12-31T02:00:33Z" level=info msg="Created plugin 05-HubController (daemon, handles CreateContainer)"
time="2024-12-31T02:00:33Z" level=info msg="Stopping plugin 05-HubController..."
E1231 02:00:33.185057       1 hub.go:57] server exist, errmsg: failed to connect to NRI service: dial unix /var/run/nri/nri.sock: connect: no such file or directory
time="2024-12-31T02:00:34Z" level=info msg="Created plugin 05-HubController (daemon, handles CreateContainer)"
time="2024-12-31T02:00:34Z" level=info msg="Stopping plugin 05-HubController..."
E1231 02:00:34.328538       1 hub.go:57] server exist, errmsg: failed to connect to NRI service: dial unix /var/run/nri/nri.sock: connect: no such file or directory
time="2024-12-31T02:00:35Z" level=info msg="Created plugin 05-HubController (daemon, handles CreateContainer)"
time="2024-12-31T02:00:35Z" level=info msg="Stopping plugin 05-HubController..."
E1231 02:00:35.733496       1 hub.go:57] server exist, errmsg: failed to connect to NRI service: dial unix /var/run/nri/nri.sock: connect: no such file or directory
time="2024-12-31T02:00:38Z" level=info msg="Created plugin 05-HubController (daemon, handles CreateContainer)"
time="2024-12-31T02:00:38Z" level=info msg="Stopping plugin 05-HubController..."
E1231 02:00:38.081280       1 hub.go:57] server exist, errmsg: failed to connect to NRI service: dial unix /var/run/nri/nri.sock: connect: no such file or directory
time="2024-12-31T02:00:40Z" level=info msg="Created plugin 05-HubController (daemon, handles CreateContainer)"
time="2024-12-31T02:00:40Z" level=info msg="Stopping plugin 05-HubController..."
E1231 02:00:40.521144       1 hub.go:57] server exist, errmsg: failed to connect to NRI service: dial unix /var/run/nri/nri.sock: connect: no such file or directory
time="2024-12-31T02:00:44Z" level=info msg="Created plugin 05-HubController (daemon, handles CreateContainer)"
time="2024-12-31T02:00:44Z" level=info msg="Stopping plugin 05-HubController..."
E1231 02:00:44.799859       1 hub.go:57] server exist, errmsg: failed to connect to NRI service: dial unix /var/run/nri/nri.sock: connect: no such file or directory
time="2024-12-31T02:00:54Z" level=info msg="Created plugin 05-HubController (daemon, handles CreateContainer)"
time="2024-12-31T02:00:54Z" level=info msg="Stopping plugin 05-HubController..."
E1231 02:00:54.212419       1 hub.go:57] server exist, errmsg: failed to connect to NRI service: dial unix /var/run/nri/nri.sock: connect: no such file or directory
`
daemonset yaml
`[root@instance-uvlkm0 kcrowdaemon]# helm template kcrow ./ --show-only templates/daemonset.yaml 
---
# Source: kcrow/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kcrow-controller
  namespace: "default"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kcrow
      app.kubernetes.io/instance: kcrow
      app.kubernetes.io/component: kcrow-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kcrow
        app.kubernetes.io/instance: kcrow
        app.kubernetes.io/component: kcrow-controller
    spec:
      priorityClassName: system-node-critical
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      restartPolicy: Always
      tolerations:
      - operator: Exists
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: kcrow-controller
        image: "ghcr.io/kcrow-io/kcrow/daemon:v1.0.0-pfx"
        imagePullPolicy: IfNotPresent
        command:
        - /usr/bin/daemon
        args:
        - daemon
        - --kubeconfig=/opt/kubeconfig
        resources:
          limits:
            cpu: 500m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 64Mi
        lifecycle:
          preStop:
            exec:
              command:
                - /usr/bin/daemon
                - shutdown
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - mountPath: /opt/kubeconfig
          name: kubeconfig
          readOnly: true
        - mountPath: /run/nri/nri.sock
          name: socket
          readOnly: true
      volumes:
      - name: kubeconfig
        hostPath:
          path: /etc/kubernetes/kubeconfig.yaml
          type: File
      - name: socket
        hostPath:
          path: /run/nri/nri.sock
          type: File`

**Comment by Frank-svg-dev** [comment]
pr : https://github.com/kcrow-io/kcrow/pull/22

**Comment by yylt** [comment]
thanks
